service: figgy-observability

provider:
  name: aws
  runtime: python3.8
  deploymentBucket: ${opt:stage}-figgy-deploy
  region: us-east-1

package:
    individually: true


plugins:
  - serverless-package-python-functions
  - serverless-api-gateway-throttling
  - serverless-domain-manager
  - serverless-plugin-log-retention
custom:
  pkgPyFuncs:
    buildDir: _build
    requirementsFile: 'requirements.txt'
    globalRequirements:
      - ./requirements.txt
    globalIncludes:
      - ./lib
    cleanup: true
    logRetentionInDays: 14

  customDomain:
    domainName: api.figgy.dev
    basePath: ''
    stage: prod
    certificateName: '*.figgy.dev'
    endpointType: 'regional'
    securityPolicy: tls_1_2
    apiType: rest

  # Configures throttling settings for all http endpoints
  apiGatewayThrottling:
    maxRequestsPerSecond: 100
    maxConcurrentRequests: 10

functions:
  log_error:
    name: figgy-obs-log-error
    role: arn:aws:iam::${ssm:/figgy/account_id}:role/figgy-obs-log-error
    handler: main.handle
    timeout: 3
    memorySize: 128
    events:
      - http:
          path: /v1/log-error
          method: post
          throttling:
            maxRequestsPerSecond: 10
            maxConcurrentRequests: 5

    package:
      include:
        - functions/log_error
      artifact: ${self:custom.pkgPyFuncs.buildDir}/figgy-obs-log-error.zip

  get_version:
    name: figgy-get-version
    role: arn:aws:iam::${ssm:/figgy/account_id}:role/figgy-get-version
    handler: main.handle
    timeout: 3
    memorySize: 128
    events:
      - http:
          path: /v1/version
          method: get
          throttling:
            maxRequestsPerSecond: 50
            maxConcurrentRequests: 10
    package:
      include:
        - functions/get_version
      artifact: ${self:custom.pkgPyFuncs.buildDir}/figgy-get-version.zip

  log_usage:
    name: figgy-obs-log-metrics
    role: arn:aws:iam::${ssm:/figgy/account_id}:role/figgy-obs-log-metrics
    handler: main.handle
    timeout: 3
    memorySize: 128
    events:
      - http:
          path: /v1/log-metrics
          method: post
          throttling:
            maxRequestsPerSecond: 50
            maxConcurrentRequests: 10
    package:
      include:
        - functions/log_usage
      artifact: ${self:custom.pkgPyFuncs.buildDir}/figgy-obs-log-metrics.zip