name: Build

on:
  push:
    branches: [develop, master]
  pull_request:
    branches: [develop, master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Deploy
        env:
          OVERRIDE_KEYRING: true
          CONFIG_FILE: ${{ secrets.CONFIG_FILE }}
          CREDS_FILE: ${{ secrets.CREDS_FILE }}
        run: |
          # Write out the [figgy-qa] profile with valid credentials
          mkdir -p ~/.aws
          echo "$CONFIG_FILE" > ~/.aws/config
          echo "$CREDS_FILE" > ~/.aws/credentials

          sudo apt -y install npm

          curl -o- -L https://slss.io/install | bash
          export PATH="$HOME/.serverless/bin:$PATH"

          env="dev"
          branch_name=${GITHUB_REF##*/}

          if [[ $branch_name = "master" ]]; then
            env="prod"
          fi

          cd serverless/
          serverless plugin install --name serverless-package-python-functions --aws-profile "figgy-${env}" --stage "${env}"
          serverless plugin install --name serverless-api-gateway-throttling --aws-profile "figgy-${env}" --stage "${env}"
          serverless plugin install --name serverless-domain-manager --aws-profile "figgy-${env}" --stage "${env}"
          serverless plugin install --name serverless-plugin-log-retention --aws-profile "figgy-${env}" --stage "${env}"


          sls deploy --aws-profile "figgy-${env}" --stage "${env}"